"""remove service_period relationship from transactions

Revision ID: c5aabb9221f4
Revises: 0a9c93ae7c55
Create Date: 2025-12-21 18:04:32.673011
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5aabb9221f4"
down_revision = "0a9c93ae7c55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop column - SQLite batch mode will recreate table without the foreign key
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("idx_transaction_period")
        batch_op.drop_column("service_period_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back column - SQLite batch mode will recreate table with the foreign key
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("service_period_id", sa.INTEGER(), nullable=True))
        batch_op.create_index("idx_transaction_period", ["service_period_id"], unique=False)
    # ### end Alembic commands ###
