"""Main application entry point."""

import asyncio
import logging
import os
from pathlib import Path
from typing import Optional

import uvicorn
from dotenv import load_dotenv
from telegram.ext import Application

from src.api.webhook import app, setup_webhook_route
from src.bot import create_bot_app
from src.services.logging import setup_server_logging


def _load_environment() -> None:
    """Load environment variables from .env and dynamic sources.

    Priority:
    1. .env (static configuration - single source of truth)
    2. /tmp/.sosenki-env (dynamic values from setup-environment.sh)
    3. OS environment variables
    """
    # Load static config from .env
    load_dotenv()

    # Load dynamic environment if it exists (generated by setup-environment.sh)
    temp_env_file = Path("/tmp/.sosenki-env")
    if temp_env_file.exists():
        load_dotenv(temp_env_file, override=True)


def _validate_environment() -> None:
    """Validate required environment variables are set.

    Mini app is core functionality - cannot run without it.
    """
    mini_app_url = os.getenv("MINI_APP_URL", "").strip()
    if not mini_app_url:
        logger.critical(
            "MINI_APP_URL not set. Application cannot start.\n"
            "For local development, run: make serve\n"
            "For production, ensure MINI_APP_URL is set in environment."
        )
        raise RuntimeError("MINI_APP_URL environment variable is required")
    logger.info("✓ MINI_APP_URL configured: %s", mini_app_url)


# Load environment variables FIRST (so LOG_LEVEL is available)
_load_environment()

# Configure logging with LOG_LEVEL from environment
setup_server_logging()
logger = logging.getLogger(__name__)

# Validate required environment variables
_validate_environment()

# Global bot application instance
bot_app: Optional[Application] = None


async def initialize_bot() -> None:
    """Initialize and setup the Telegram bot."""
    global bot_app
    logger.info("Initializing Telegram bot...")
    bot_app = await create_bot_app()

    logger.info("Bot initialized successfully")


async def run_webhook_mode(host: str = "0.0.0.0", port: int = 8000):
    """Run application in webhook mode (production)."""
    logger.info(f"Starting bot in webhook mode on {host}:{port}")

    global bot_app

    # Create but don't initialize bot yet - will be done in FastAPI startup
    bot_app = await create_bot_app()

    # Setup webhook route with the bot app
    await setup_webhook_route(bot_app)

    # Initialize bot immediately before starting server
    # This ensures bot is ready before any requests arrive
    logger.info("Initializing bot Application...")
    await bot_app.initialize()
    logger.info("Bot Application initialized")

    # Register webhook URL with Telegram
    webhook_url = os.getenv("WEBHOOK_URL", "").strip()
    if webhook_url:
        logger.info(f"Setting Telegram webhook to {webhook_url}")
        try:
            await bot_app.bot.set_webhook(url=webhook_url, drop_pending_updates=True)
            logger.info("Webhook registered successfully with Telegram")
        except Exception as e:
            logger.error(f"Failed to set webhook: {e}", exc_info=True)
    else:
        logger.warning("WEBHOOK_URL not set in environment")

    async def shutdown_bot():
        global bot_app
        if bot_app:
            try:
                await bot_app.shutdown()
                logger.info("Bot Application shutdown complete")
            except Exception as e:
                logger.error(f"Error shutting down bot: {e}")

    # Register shutdown with FastAPI
    app.add_event_handler("shutdown", shutdown_bot)

    logger.info(f"Starting Uvicorn server on {host}:{port}...")
    config = uvicorn.Config(
        app=app,
        host=host,
        port=port,
        log_level="info",
        timeout_graceful_shutdown=1,  # Force shutdown after 1 second
    )
    server = uvicorn.Server(config)
    await server.serve()


async def run_polling_mode(host: str = "0.0.0.0", port: int = 8000):
    """Run application in polling mode (no public webhook URL required).

    The FastAPI webapp (Mini App API) always runs alongside the polling bot.
    """
    logger.info(f"Starting bot in polling mode on {host}:{port}")

    global bot_app

    bot_app = await create_bot_app()

    # Wire bot into FastAPI so Mini App API routes have access to it
    await setup_webhook_route(bot_app)

    logger.info("Initializing bot Application...")
    await bot_app.initialize()
    logger.info("Bot Application initialized")

    # Clear any stale webhook registration with Telegram
    await bot_app.bot.delete_webhook(drop_pending_updates=True)
    logger.info("Telegram webhook cleared")

    # Start polling (PTB v20 async — starts background task, non-blocking)
    await bot_app.updater.start_polling(drop_pending_updates=True)
    await bot_app.start()
    logger.info("Bot polling started")

    async def shutdown_bot():
        global bot_app
        if bot_app:
            try:
                await bot_app.updater.stop()
                await bot_app.stop()
                await bot_app.shutdown()
                logger.info("Bot Application shutdown complete")
            except Exception as e:
                logger.error(f"Error shutting down bot: {e}")

    # Register shutdown with FastAPI
    app.add_event_handler("shutdown", shutdown_bot)

    logger.info(f"Starting Uvicorn server on {host}:{port}...")
    config = uvicorn.Config(
        app=app,
        host=host,
        port=port,
        log_level="info",
        timeout_graceful_shutdown=1,
    )
    server = uvicorn.Server(config)
    await server.serve()


def main():
    """Main entry point."""
    import argparse

    # Get port from environment (required)
    port_env = os.getenv("PORT")
    if not port_env:
        logger.critical("PORT not set in environment. Check .env file.")
        raise RuntimeError("PORT environment variable is required")
    default_port = int(port_env)

    parser = argparse.ArgumentParser(description="SOSenki Bot")
    parser.add_argument("--host", default="0.0.0.0", help="Host to bind to")
    parser.add_argument("--port", type=int, default=default_port, help="Port to bind to")

    args = parser.parse_args()

    # Auto-detect mode: webhook if WEBHOOK_URL is set, polling otherwise
    webhook_url = os.getenv("WEBHOOK_URL", "").strip()
    if webhook_url:
        logger.info("WEBHOOK_URL set — starting in webhook mode")
        run = run_webhook_mode(args.host, args.port)
    else:
        logger.info("WEBHOOK_URL not set — starting in polling mode")
        run = run_polling_mode(args.host, args.port)

    try:
        asyncio.run(run)
    except KeyboardInterrupt:
        logger.info("Server stopped by user")
        raise SystemExit(0) from None
    except asyncio.CancelledError:
        logger.info("Server shutdown complete")
        raise SystemExit(0) from None


if __name__ == "__main__":
    main()
